"Resource/UI/Build_Menu/HudMenuEngyBuild.res"
{
	"active_item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"active_item_1"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"34"
		"visible"									"1"
	}
	"active_item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"active_item_2"
		"xpos"										"0"
		"ypos"										"36"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"active_item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"active_item_3"
		"xpos"										"0"
		"ypos"										"64"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"active_item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"active_item_4"
		"xpos"										"0"
		"ypos"										"92"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"already_built_item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"already_built_item_1"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"already_built_item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"already_built_item_2"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"already_built_item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"already_built_item_3"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"already_built_item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"already_built_item_4"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"cant_afford_item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"cant_afford_item_1"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"34"
		"visible"									"0"
	}
	"cant_afford_item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"cant_afford_item_2"
		"xpos"										"0"
		"ypos"										"36"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"cant_afford_item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"cant_afford_item_3"
		"xpos"										"0"
		"ypos"										"64"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"cant_afford_item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"cant_afford_item_4"
		"xpos"										"0"
		"ypos"										"92"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"unavailable_item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"unavailable_item_1"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"unavailable_item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"unavailable_item_2"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"unavailable_item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"unavailable_item_3"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"unavailable_item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"unavailable_item_4"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
}