"Resource/UI/Build_Menu/HudMenuEngyBuild.res"
{
	"Active_Item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Active_Item_1"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"34"
		"visible"									"1"
	}
	"Active_Item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Active_Item_2"
		"xpos"										"0"
		"ypos"										"36"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"Active_Item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Active_Item_3"
		"xpos"										"0"
		"ypos"										"64"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"Active_Item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Active_Item_4"
		"xpos"										"0"
		"ypos"										"92"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"1"
	}
	"Already_Built_Item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Already_Built_Item_1"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Already_Built_Item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Already_Built_Item_2"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Already_Built_Item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Already_Built_Item_3"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Already_Built_Item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Already_Built_Item_4"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Cant_Afford_Item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Cant_Afford_Item_1"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"34"
		"visible"									"0"
	}
	"Cant_Afford_Item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Cant_Afford_Item_2"
		"xpos"										"0"
		"ypos"										"36"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"Cant_Afford_Item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Cant_Afford_Item_3"
		"xpos"										"0"
		"ypos"										"64"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"Cant_Afford_Item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Cant_Afford_Item_4"
		"xpos"										"0"
		"ypos"										"92"
		"zpos"										"1"
		"wide"										"34"
		"tall"										"26"
		"visible"									"0"
	}
	"Unavailable_Item_1"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Unavailable_Item_1"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Unavailable_Item_2"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Unavailable_Item_2"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Unavailable_Item_3"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Unavailable_Item_3"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
	"Unavailable_Item_4"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"Unavailable_Item_4"
		"xpos"										"9999"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
	}
}