"Resource/UI/HudTournamentSetup.res"
{
	"TournamentNameEdit"
	{
		"ControlName"								"TextEntry"
		"fieldName"									"TournamentNameEdit"
		"xpos"										"cs-0.5"
		"ypos"										"rs1"
		"wide"										"f4"
		"tall"										"12"
		"visible"									"1"
		"enabled"									"1"
		"textHidden"								"0"
		"editable"									"1"
		"maxchars"									"6"
		"NumericInputOnly"							"0"
		"unicode"									"0"
		"wrap"										"0"
		"RoundedCorners"							"0"
		"proportionaltoparent"						"1"
		"font" 										"StorePromotionsTitle"
		"fgcolor_override"							"White"
		"bgcolor_override"							"TransparentLightBlack"
		"labelText"									"%teamname%"
		"textAlignment"								"center"
	}
	"TournamentReadyButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"TournamentReadyButton"
		"xpos"										"rs1"
		"ypos"										"0"
		"wide"										"p0.35"
		"tall"										"12"
		"zpos"										"0"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"Ready"
		"textAlignment"								"east"
		"command"									"teamready"
		"default"									"0"
		"proportionaltoparent"						"1"
		"font"										"FontStorePrice"
		"fgcolor"									"White"
		"defaultFgColor_override" 					"White"
		"armedFgColor_override" 					"Main"
		"depressedFgColor_override"					"Main"
		"selectedFgColor_override" 					"Main"
		"paintbackground"							"0"
	}
	"TournamentNotReadyButton"
	{
		"ControlName"								"CExButton"
		"fieldName"									"TournamentNotReadyButton"
		"xpos"										"0"
		"ypos"										"0"
		"wide"										"p0.65"
		"tall"										"12"
		"zpos"										"0"
		"visible"									"1"
		"enabled"									"1"
		"labelText"									"Not Ready -"
		"textAlignment"								"west"
		"command"									"teamnotready"
		"default"									"1"
		"proportionaltoparent"						"1"
		"font"										"FontStorePrice"
		"fgcolor"									"White"
		"defaultFgColor_override" 					"White"
		"armedFgColor_override" 					"HUDRedTeamSolid"
		"depressedFgColor_override" 				"HUDRedTeamSolid"
		"selectedFgColor_override" 					"HUDRedTeamSolid"
		"paintbackground"							"0"
	}


	"HudTournamentSetupBG"
	{
		"ControlName"								"ScalableImagePanel"
		"fieldName"									"HudTournamentSetupBG"
		"xpos"										"9999"
	}
	"TournamentSetupLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TournamentSetupLabel"
		"xpos"										"9999"
	}
	"TournamentTeamNameLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TournamentTeamNameLabel"
		"xpos"										"9999"
	}
	"HudTournamentNameBG"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"HudTournamentNameBG"
		"xpos"										"9999"
	}
}